# Generated by Django 6.0.2 on 2026-02-25 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
